### ISSUE TITLE
Passport object undefined

### ISSUE THREAD

**Issue by fenichelar** [tjwebb/sails-auth#127]
When logging in I get an error. I am using Google Auth. The error is produced during the following block in `passport.js`:

```
  // Scenario: An existing user is trying to log in using an already
  //           connected passport.
  // Action:   Get the user associated with the passport.
  else {
    // If the tokens have changed since the last session, update them
    if (_.has(query, 'tokens') && query.tokens != passport.tokens) {
      passport.tokens = query.tokens;
    }

    // Save any updates to the Passport before moving on
    return passport.save()
      .then(function (passport) {

        // Fetch the user associated with the Passport
        return sails.models.user.findOne(passport.user.id);
      })
      .then(function (user) {
        next(null, user);
      })
      .catch(next);
  }
```

`return sails.models.user.findOne(passport.user.id);` errors because `passport` is undefined. Any ideas how to fix?

**Comment by fruedaCode** [comment]
I'm having the same issue. Any solution??

Thanks!

**Comment by pawelhertman** [comment]
@fenichelar @fruedaCode did you solve this problem?

**Comment by fruedaCode** [comment]
solve it! thanks!

2016-11-17 13:16 GMT+01:00 Paweł Hertman notifications@github.com:

**Comment by pawelhertman** [comment]
@fenichelar could you write how did you do that? I know it is fixed in 2.1.4 version, but the latest version of sails-auth in npm is 2.1.3. I tried to install v2.1.4 directly from repository, but I've got an error "cannot find module 'node_modules/sails-auth'" (although it exists)

**Comment by pawelhertman** [comment]
@fruedaCode could you write how did you do that? I know it has been fixed in 2.1.4 version, but the latest version of sails-auth in npm is 2.1.3. I tried to install v2.1.4 directly from repository, but I've got an error "cannot find module 'node_modules/sails-auth'" (although it exists)

**Comment by fruedaCode** [comment]
I directly changed that line on dist directory. But i think you could extend passport module and override the function.

**Comment by jorgecasar** [comment]
Solved by #128 and released on [v2.1.4](https://github.com/langateam/sails-auth/releases/tag/v2.1.4).

Please @tjwebb, could you publish on NPM the versions 2.1.4 and above?

**Comment by jorgecasar** [comment]
Installing with `npm i --save langateam/sails-auth` npm install it but when I launch sails I get this error. Any idea?

```
error: Error: Cannot find module '[PROJECT_ABSOLUTE_PATH]/node_modules/sails-auth'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at [PROJECT_ABSOLUTE_PATH]/node_modules/sails/lib/hooks/moduleloader/index.js:609:26
    at [PROJECT_ABSOLUTE_PATH]/node_modules/@sailshq/lodash/lib/index.js:2678:13
    at [PROJECT_ABSOLUTE_PATH]/node_modules/@sailshq/lodash/lib/index.js:3228:15
    at baseForOwn ([PROJECT_ABSOLUTE_PATH]/node_modules/@sailshq/lodash/lib/index.js:2199:14)
    at [PROJECT_ABSOLUTE_PATH]/node_modules/@sailshq/lodash/lib/index.js:3198:18
    at baseReduce ([PROJECT_ABSOLUTE_PATH]/node_modules/@sailshq/lodash/lib/index.js:2675:7)
    at Function.<anonymous> ([PROJECT_ABSOLUTE_PATH]/node_modules/@sailshq/lodash/lib/index.js:3601:13)
    at [PROJECT_ABSOLUTE_PATH]/node_modules/sails/lib/hooks/moduleloader/index.js:562:29
    at [PROJECT_ABSOLUTE_PATH]/node_modules/sails/node_modules/async/lib/async.js:52:16
    at [PROJECT_ABSOLUTE_PATH]/node_modules/sails/node_modules/async/lib/async.js:548:17
    at [PROJECT_ABSOLUTE_PATH]/node_modules/sails/node_modules/async/lib/async.js:542:17
    at _arrayEach ([PROJECT_ABSOLUTE_PATH]/node_modules/sails/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete ([PROJECT_ABSOLUTE_PATH]/node_modules/sails/node_modules/async/lib/async.js:541:13)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```
