### ISSUE TITLE
Cannot find module when files are pulled from repo

### ISSUE THREAD

**Issue by enuggetry** [tjwebb/sails-auth#166]
Why is it when I pull directly from the repo, I get this message when I lift?

```
[root@osboxes testm]# sails lift

info: Starting app...

error: Error: Cannot find module '/var/www/html/testm/node_modules/sails-auth'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)

```
I had added this to package.json
```
  "dependencies": {
    "sails-auth" : "git://github.com/trailsjs/sails-auth.git#f425b254e1249cb186e3ee19718eb916c5f080e2",

```

**Comment by enuggetry** [comment]
the problem was it was not building the dist directory because I was logged in as root.  Should not happen as a non-root user with appropriate sudo permission.  Can also be forced with `npm install --unsafe-perm`
