### ISSUE TITLE
Error out of the box

### ISSUE THREAD

**Issue by htondkar** [tjwebb/sails-auth#168]
I installed the generator and started a new project, i chose express and sequlize, after installation of dependencies, i tried to start the app with npm start, but there was an error: 

`TypeError: Cannot read property 'warn' of undefined
    at SequelizeTrailpack.validate (/home/hamid/Projects/Personal/trails/node_modules/trailpack-sequelize/index.js:18:34)
    at app.after.then.then (/home/hamid/Projects/Personal/trails/node_modules/trails/lib/Core.js:191:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Error: config.web.express is absent, please npm install your express version (4 or 5) and uncomment the line under config.web.express
    at Express.validate (/home/hamid/Projects/Personal/trails/node_modules/trailpack-express/index.js:29:9)
    at app.after.then.then (/home/hamid/Projects/Personal/trails/node_modules/trails/lib/Core.js:191:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
(node:9643) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'warn' of undefined
(node:9643) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9643) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: config.web.express is absent, please npm install your express version (4 or 5) and uncomment the line under config.web.express`

**Comment by htondkar** [comment]
Also tried Hapi with sequlize and here is the error: 
`TypeError: Cannot read property 'warn' of undefined
    at SequelizeTrailpack.validate (/home/hamid/Projects/Personal/trails/node_modules/trailpack-sequelize/index.js:18:34)
    at app.after.then.then (/home/hamid/Projects/Personal/trails/node_modules/trails/lib/Core.js:191:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
(node:10403) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'warn' of undefined
(node:10403) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by htondkar** [comment]
Then i chose Hapi + waterline, there is no error but nothing happens when a start the server

**Comment by htondkar** [comment]
Basically nothing works, at all

**Comment by htondkar** [comment]
Tnx
