### ISSUE TITLE
posting to auth/local on fresh install returns error

### ISSUE THREAD

**Issue by bgulotta** [tjwebb/sails-auth#20]
I'm getting the error below on a clean install of sails-auth and sails-permissions. It happens when I attempt to post to /auth/local with the default admin credentials  { email: 'admin@example.com' password:'admin1234'}.

Error: Failed to serialize user into session
    at pass (/Users/bgulotta/git/reach-api/node_modules/sails-auth/node_modules/passport/lib/authenticator.js:277:19)

**Comment by bmsterling** [comment]
It may or may not be related, but I'm erroring out when logging in with a fresh install as well, except my error is `Error: passport.initialize() middleware not in use`.  Both the session issue and mine seem to be related to the `api/policies/passport.js` file not actually being executed.  It's being loaded, but `passport.initialize`, which in turn calls `passport.session`, never being called.

I'm still trying to grasp how sails loads and executes things and I'll keep debugging, but guidance would be helpful.

**Comment by tjwebb** [comment]
There's another open issue for this as well. I'll try to get to it today.

**Comment by bmsterling** [comment]
Thanks, let me know if I can help.

**Comment by tjwebb** [comment]
There were a couple other related issues both here and in sails-permissions that I resolved today. Specifically, the policies config in the sails-permissions README was out of date.

Can you guys update your policies config according to the new README and test this out again?

**Comment by bgulotta** [comment]
sure...

**Comment by bgulotta** [comment]
I'm still getting the serialization error trying to post to auth/local with the default admin user.

[Error: Failed to serialize user into session]

**Comment by tjwebb** [comment]
Ok I'll check this out.

**Comment by bgulotta** [comment]
![screen shot 2015-03-17 at 11 32 12 am](https://cloud.githubusercontent.com/assets/3649271/6692310/00976b64-cc9a-11e4-8041-4ec014d04601.png)

```
warn: Error: Failed to serialize user into session
    at pass (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/authenticator.js:277:19)
    at serialized (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/authenticator.js:282:7)
    at module.exports (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/api/services/passport.js:354:3)
    at pass (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/authenticator.js:290:9)
    at Authenticator.serializeUser (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/authenticator.js:295:5)
    at IncomingMessage.req.login.req.logIn (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/http/request.js:48:29)
    at /Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/api/controllers/AuthController.js:93:11
    at allFailed (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/middleware/authenticate.js:87:18)
    at attempt (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/middleware/authenticate.js:160:28)
    at Strategy.strategy.fail (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/middleware/authenticate.js:277:9)
    at Strategy.authenticate (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport-local/lib/strategy.js:75:17)
    at attempt (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Authenticator.passport.callback (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/api/services/passport.js:251:40)
    at Authenticator.bound [as callback] (/Users/bgulotta/git/reach/dev-api/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Object.module.exports.callback (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/api/controllers/AuthController.js:87:14)
    at bound (/Users/bgulotta/git/reach/dev-api/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at routeTargetFnWrapper (/Users/bgulotta/git/reach/dev-api/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/Users/bgulotta/git/reach/dev-api/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/bgulotta/git/reach/dev-api/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/Users/bgulotta/git/reach/dev-api/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/bgulotta/git/reach/dev-api/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/bgulotta/git/reach/dev-api/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/bgulotta/git/reach/dev-api/node_modules/sails/lib/router/bind.js:187:7
    at /Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/api/policies/passport.js:37:7
    at SessionStrategy.strategy.pass (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/middleware/authenticate.js:318:9)
    at SessionStrategy.authenticate (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/strategies/session.js:67:10)
    at attempt (/Users/bgulotta/git/reach/dev-api/node_modules/sails-auth/node_modules/passport/lib/middleware/authenticate.js:341:16) [Error: Failed to serialize user into session]

```
In case it is helpful, screenshot of REST call and stack trace

**Comment by bgulotta** [comment]
It appears that the issue is that the call to passports this.authenticate() isn't calling your local.login method. I'll do a little more digging and see why this is not the case.

I made a small change to force the login method to get called on the local provider and the login seems to work just fine. 

```
      // The provider will redirect the user to this URL after approval. Finish
      // the authentication process by attempting to obtain an access token. If
      // access was granted, the user will be logged in. Otherwise, authentication
      // has failed.
      this.protocols.local.login(req, req.body.email, req.body.password, function(err, user) {

        if (err || !user)
          res.forbidden();
        else
          res.json(user);
      });

      //this.authenticate(provider, next)(req, res, req.next);

```

**Comment by bgulotta** [comment]
I figured out the issue and got the local authentication to work. I believe there just needs to be a documentation update. It needs to say to make sure the field in your post to auth/login is called "identifier" and not username or email. There is another issue I'll open in another thread. If you submit an invalid identifier or password when authenticating the rest call isn't returning a response to the client.

**Comment by bgulotta** [comment]
Now that I think about it I would expect posting to auth/local or any endpoint in sails with invalid request values to return res.badRequest()

**Comment by tjwebb** [comment]
Yes it should. Sounds like an oversight on my part.
