### ISSUE TITLE
after fresh install, a visit to /auth/google produces error

### ISSUE THREAD

**Issue by phishy** [tjwebb/sails-auth#25]
```
/Users/jeff/www/test-sails/node_modules/sails-auth/node_modules/passport/lib/http/request.js:44
    if (!this._passport) { throw new Error('passport.initialize() middleware n
                                 ^
Error: passport.initialize() middleware not in use
    at IncomingMessage.req.login.req.logIn (/Users/jeff/www/test-sails/node_modules/sails-auth/node_modules/passport/lib/http/request.js:44:34)
    at /Users/jeff/www/test-sails/node_modules/sails-auth/api/controllers/AuthController.js:93:11
    at Strategy.strategy.success (/Users/jeff/www/test-sails/node_modules/sails-auth/node_modules/passport/lib/middleware/authenticate.js:194:18)
    at verified (/Users/jeff/www/test-sails/node_modules/sails-auth/node_modules/passport-google/node_modules/passport-openid/lib/passport-openid/strategy.js:194:14)
    at /Users/jeff/www/test-sails/node_modules/sails-auth/api/services/passport.js:135:13
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:241:9
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:157:25
    at null.<anonymous> (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44)
```

**Comment by tjwebb** [comment]
Sorry I just saw this. What version of sails-auth are you using?

**Comment by tjwebb** [comment]
Do you have this in config/policies.js:

```js
  '*': [ 'basicAuth', 'passport', 'sessionAuth' ],
```

**Comment by tjwebb** [comment]
Resolved: https://github.com/tjwebb/sails-auth/issues/26#issuecomment-82076072.
