### ISSUE TITLE
Lifting the app after the first time throws errors trying to create an admin user that already exists

### ISSUE THREAD

**Issue by secrettriangle** [tjwebb/sails-auth#46]
```
$ sails lift

info: Starting app...

debug: sails-permissions: syncing waterline models
debug: sails-permissions: admin user does not exist; creating...
debug: Error (E_VALIDATION) :: 2 attributes are invalid
    at WLValidationError.WLError (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/WLError.js:26:15)
    at new WLValidationError (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/WLValidationError.js:20:28)
    at duckType (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/index.js:60:12)
    at errorify (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/index.js:39:10)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:325:15)
    at callback.error (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:46:28)
    at null._onTimeout (/usr/local/lib/node_modules/sails/node_modules/sails-disk/lib/adapter.js:179:10)
    at Timer.listOnTimeout (timers.js:110:15)

Invalid attributes sent to undefined:
 • username
   • A record with that `username` already exists (`admin@example.com`).
 • email
   • A record with that `email` already exists (`admin@example.com`).

error: Error: Error.Passport.Email.Exists
    at /Users/dan/stuff/sails-auth/api/services/protocols/local.js:45:23
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:216:14
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:331:16)
    at callback.error (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:46:28)
    at afterwards (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:88:16)
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:331:16)
    at callback.error (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:46:28)
    at null._onTimeout (/usr/local/lib/node_modules/sails/node_modules/sails-disk/lib/adapter.js:179:10)
    at Timer.listOnTimeout (timers.js:110:15)
From previous event:
    at bound.module.exports.register (/Users/dan/stuff/sails-auth/api/models/User.js:42:12)
    at bound [as register] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/dan/stuff/sails-permissions/config/fixtures/user.js:20:19
    at processImmediate [as _immediateCallback] (timers.js:358:17) [Error: Error.Passport.Email.Exists]
```

**Comment by tjwebb** [comment]
What adapter and sails-auth version are you using? I haven't seen this.

**Comment by tjwebb** [comment]
Is this still an issue?

**Comment by dbkaplun** [comment]
Yes it is. This happens on `master`, with the `sails-disk` adapter. You should be able to repro:
```sh
npm install dbkaplun/nodegolf
cd node_modules/nodegolf
sails lift # wait until it's loaded, then Ctrl+C to quit
sails lift # run a second time -- the first time won't work as the admin user wasn't created yet
```
