### ISSUE TITLE
Major issue, sails shuts down completely after GET instead of POST request to /auth/local

### ISSUE THREAD

**Issue by dbkaplun** [tjwebb/sails-auth#47]
```js
io.socket.get('/auth/local', {identifier: 'dan@secrettriangle.net', password: 'asdfasdf'}, function () { console.log('user', arguments); });
```

```
info:
info:                .-..-.
info:
info:    Sails              <|    .-..-.
info:    v0.11.0             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------'
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info:
info: Server lifted in `/Users/dan/stuff/nodegolf`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Thu May 14 2015 19:16:23 GMT-0400 (EDT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
/Users/dan/stuff/sails-auth/node_modules/passport/lib/middleware/authenticate.js:229
          if (err) { return next(err); }
                            ^
TypeError: undefined is not a function
    at /Users/dan/stuff/sails-auth/node_modules/passport/lib/middleware/authenticate.js:229:29
    at /Users/dan/stuff/sails-auth/node_modules/passport/lib/http/request.js:49:48
    at pass (/Users/dan/stuff/sails-auth/node_modules/passport/lib/authenticator.js:293:14)
    at Authenticator.serializeUser (/Users/dan/stuff/sails-auth/node_modules/passport/lib/authenticator.js:295:5)
    at Authenticator.bound [as serializeUser] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at MockIncomingMessage.req.login.req.logIn (/Users/dan/stuff/sails-auth/node_modules/passport/lib/http/request.js:48:29)
    at Strategy.strategy.success (/Users/dan/stuff/sails-auth/node_modules/passport/lib/middleware/authenticate.js:228:13)
    at verified (/Users/dan/stuff/sails-auth/node_modules/passport-local/lib/strategy.js:83:10)
    at /Users/dan/stuff/sails-auth/api/services/protocols/local.js:167:20
    at /Users/dan/stuff/sails-auth/node_modules/bcryptjs/dist/bcrypt.js:230:13
    at /Users/dan/stuff/sails-auth/node_modules/bcryptjs/dist/bcrypt.js:1167:21
    at Immediate.next [as _onImmediate] (/Users/dan/stuff/sails-auth/node_modules/bcryptjs/dist/bcrypt.js:1047:21)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by tjwebb** [comment]
Do you still run into this?

**Comment by dbkaplun** [comment]
Nope!
