### ISSUE TITLE
Attempted to `POST /register` with `identifier=admin@example.com&password=admin1234` shuts down server

### ISSUE THREAD

**Issue by secrettriangle** [tjwebb/sails-auth#49]
Attempted to `POST /register` with `identifier=admin@example.com&password=admin1234` instead of `email=admin@example.com&password=admin1234`...

```
$ sails lift

info: Starting app...

-----------------------------------------------------------------

 Excuse my interruption, but it looks like this app
 does not have a project-wide "migrate" setting configured yet.
 (perhaps this is the first time you're lifting it with models?)

 In short, this setting controls whether/how Sails will attempt to automatically
 rebuild the tables/collections/sets/etc. in your database schema.
 You can read more about the "migrate" setting here:
 http://sailsjs.org/#/documentation/concepts/ORM/model-settings.html?q=migrate

 In a production environment (NODE_ENV==="production") Sails always uses
 migrate:"safe" to protect inadvertent deletion of your data.
 However during development, you have a few other options for convenience:

 1. safe  - never auto-migrate my database(s). I will do it myself (by hand)
 2. alter - auto-migrate, but attempt to keep my existing data (experimental)
 3. drop  - wipe/drop ALL my data and rebuild models every time I lift Sails

What would you like Sails to do?

info: To skip this prompt in the future, set `sails.config.models.migrate`.
info: (conventionally, this is done in `config/models.js`)

warn: ** DO NOT CHOOSE "2" or "3" IF YOU ARE WORKING WITH PRODUCTION DATA **

prompt: ?:

 Temporarily using `sails.config.models.migrate="safe"...
 (press CTRL+C to cancel-- continuing lift automatically in 0.5 seconds...)

info:
info:                .-..-.
info:
info:    Sails              <|    .-..-.
info:    v0.11.0             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------'
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info:
info: Server lifted in `/Users/dan/sails-auth-test`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Fri May 15 2015 20:29:45 GMT-0400 (EDT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
crypto.js:119
  this._handle.update(data, encoding);
               ^
TypeError: Not a string or buffer
    at TypeError (native)
    at Hash.update (crypto.js:119:16)
    at module.exports.attributes.getGravatarUrl (/Users/dan/sails-auth-test/node_modules/sails-auth/api/models/User.js:26:11)
    at module.exports.attributes.toJSON (/Users/dan/sails-auth-test/node_modules/sails-auth/api/models/User.js:33:31)
    at Object.stringify (native)
    at ServerResponse.res.json (/usr/local/lib/node_modules/sails/node_modules/express/lib/response.js:217:19)
    at ServerResponse.jsonx (/usr/local/lib/node_modules/sails/lib/hooks/responses/index.js:218:21)
    at Object.sendOK (/Users/dan/sails-auth-test/api/responses/ok.js:28:16)
    at ServerResponse.bound [as ok] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/dan/sails-auth-test/node_modules/sails-auth/api/controllers/UserController.js:13:11
    at /Users/dan/sails-auth-test/node_modules/sails-auth/api/services/protocols/local.js:71:7
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:241:9
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:157:25
    at bound.<anonymous> (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44)
    at fn (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:60:10)
    at iterate (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:149:13)

 20:29:48  ✘ 1  dan@elise:~/sails-auth-test   master ✘ ✹ 
$
```

**Comment by tjwebb** [comment]
> Attempted to POST /register with identifier=admin@example.com&password=admin1234 instead of email=admin@example.com&password=admin1234...

What is `identifier`?

**Comment by secrettriangle** [comment]
I don't think it's used by `/register`. It was an accident; my intention was to use `email` instead which `/register` picks up. However the fact that not including `email` brought down the server is cause for a Github issue. :P

**Comment by tjwebb** [comment]
> However the fact that not including email brought down the server is cause for a Github issue. :P

Indeed
