### ISSUE TITLE
Invalid email address in user creation throws 500

### ISSUE THREAD

**Issue by mitom** [tjwebb/sails-auth#58]
Trying to create a User by POSTing 
````json
{
  "username": "test",
  "email": "test@local",
  "password": "test1234"
}
````

results in a response containig `{}` with status 500 and the following logs:

````
debug: Error (E_VALIDATION) :: 1 attribute is invalid
    at WLValidationError.WLError (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/WLError.js:26:15)
    at new WLValidationError (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/WLValidationError.js:20:28)
    at /usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/validate.js:45:43
    at allValidationsChecked (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:198:5)
    at done (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:132:19)
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:32:16
    at validate (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:135:49)
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:122:13
    at _each (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:121:9)
    at Validator.validate (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:195:9)
    at async.series.runner (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/validate.js:41:25)
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:607:21
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:246:17
    at iterate (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:146:13)
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:157:25

Invalid attributes sent to User:
 • email
   • `undefined` should be a email (instead of "test@local", which is a string)

error: Sending 500 ("Server Error") response: 
 Error: Error.Passport.Email.Exists
    at /home/milka/Projects/minimoo/node_modules/sails-auth/api/services/protocols/local.js:45:23
    at /usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:73:22
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:251:17
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:148:21
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:248:21
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:612:34
    at /usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/validate.js:70:22
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:251:17
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:148:21
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:248:21
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:612:34
    at /usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/validate.js:45:40
    at allValidationsChecked (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:198:5)
    at done (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:132:19)
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:32:16
    at validate (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:135:49) [Error: Error.Passport.Email.Exists]
````

I would expect the validation error to be returned, as it is when simply using the blueprints API.

**Comment by mitom** [comment]
Apparently [all validation errors](https://github.com/tjwebb/sails-auth/blob/master/api/services/protocols/local.js#L40-L51) result in an 500 response during user creation with the local adapter.

Is this the expected behaviour..?

**Comment by tjwebb** [comment]
Yea, it should return a 400, not a 500. Some of this is residual user-unfriendiness from the sails-generate-auth module that I originally used to set all this up.

If you can submit a PR I'd really appreciate it.
