### ISSUE TITLE
App no longer works after introducing marlinspike.

### ISSUE THREAD

**Issue by shvelo** [tjwebb/sails-auth#84]
Unable to load custom protocols because sails-auth now calls loadStrategies before my protocols are loaded. 

```
throw new TypeError('JwtStrategy requires a verify callback');
              ^
TypeError: JwtStrategy requires a verify callback
  at new JwtStrategy (/home/in2circle/development/sadili.ge/node_modules/passport-jwt/lib/strategy.js:39:15)
  at /home/in2circle/development/sadili.ge/node_modules/sails-auth/dist/api/services/passport.js:328:20
  at /home/in2circle/development/sadili.ge/node_modules/sails-auth/node_modules/lodash/index.js:3073:15
  at baseForOwn (/home/in2circle/development/sadili.ge/node_modules/sails-auth/node_modules/lodash/index.js:2046:14)
  at /home/in2circle/development/sadili.ge/node_modules/sails-auth/node_modules/lodash/index.js:3043:18
  at Function.<anonymous> (/home/in2circle/development/sadili.ge/node_modules/sails-auth/node_modules/lodash/index.js:3346:13)
  at Authenticator.passport.loadStrategies (/home/in2circle/development/sadili.ge/node_modules/sails-auth/dist/api/services/passport.js:281:5)
  at Auth.configure (/home/in2circle/development/sadili.ge/node_modules/sails-auth/dist/api/hooks/auth/index.js:37:31)
  at Hook.configure (/home/in2circle/development/sadili.ge/node_modules/sails-auth/node_modules/marlinspike/dist/marlinspike.js:185:18)
  at Hook.bound [as configure] (/home/in2circle/development/sadili.ge/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
  at /home/in2circle/development/sadili.ge/node_modules/sails/lib/app/private/loadHooks.js:176:18
  at /home/in2circle/development/sadili.ge/node_modules/sails/node_modules/async/lib/async.js:122:13
  at _each (/home/in2circle/development/sadili.ge/node_modules/sails/node_modules/async/lib/async.js:46:13)
  at Object.async.each (/home/in2circle/development/sadili.ge/node_modules/sails/node_modules/async/lib/async.js:121:9)
  at Object.async.series.configure (/home/in2circle/development/sadili.ge/node_modules/sails/lib/app/private/loadHooks.js:174:17)
  at /home/in2circle/development/sadili.ge/node_modules/sails/node_modules/async/lib/async.js:620:25
  at iterate (/home/in2circle/development/sadili.ge/node_modules/sails/node_modules/async/lib/async.js:146:13)
  at /home/in2circle/development/sadili.ge/node_modules/sails/node_modules/async/lib/async.js:157:25
  at /home/in2circle/development/sadili.ge/node_modules/sails/node_modules/async/lib/async.js:626:21
  at done (/home/in2circle/development/sadili.ge/node_modules/sails/node_modules/async/lib/async.js:132:19)
  at /home/in2circle/development/sadili.ge/node_modules/sails/node_modules/async/lib/async.js:32:16
  at process._tickCallback (node.js:355:11)
```

**Comment by kevintechie** [comment]
shvelo,

This is due to a bug I mentioned. Please see my post for a fix: https://github.com/tjwebb/sails-auth/issues/79

**Comment by tjwebb** [comment]
Also, the marlinspike introduction corresponds with a new major version (2.0). I'll be working on documenting an upgrade path.

**Comment by pixelbacon** [comment]
Hitting the same snag, even after implementing [tjweb#79](https://github.com/trailsjs/sails-auth/issues/79) fix...

@shvelo Where you able to get this work?
